"""Deterministically generates the DEMO league raw CSVs (synthetic test data, not real football).

    python tests/fixtures/golden/generate_raw.py

Also writes provenance sidecars, expected checksums, and the alias store. The output is committed;
regenerate only together with an ADR explaining why golden artifacts changed.
"""

import csv
import hashlib
import json
import random
from datetime import date, timedelta
from pathlib import Path

HERE = Path(__file__).parent / "root"
TEAMS = {
    "Alpha FC": "alpha_fc",
    "Beta United": "beta_united",
    "Gamma Town": "gamma_town",
    "Delta City": "delta_city",
}
RAW_ALIAS = {"Beta United": "Beta Utd"}  # raw spelling differs from canonical for one team
SEASONS = {"2122": 2021, "2223": 2022, "2324": 2023}
HEADER = [
    "Div",
    "Date",
    "Time",
    "HomeTeam",
    "AwayTeam",
    "FTHG",
    "FTAG",
    "FTR",
    "HS",
    "AS",
    "HST",
    "AST",
    "HC",
    "AC",
    "HF",
    "AF",
    "HY",
    "AY",
    "HR",
    "AR",
    "B365H",
    "B365D",
    "B365A",
    "B365CH",
    "B365CD",
    "B365CA",
    "AvgH",
    "AvgD",
    "AvgA",
    "AvgCH",
    "AvgCD",
    "AvgCA",
]


def odds(rng):
    p = [rng.uniform(0.25, 0.55), rng.uniform(0.2, 0.3)]
    p.append(1 - sum(p))
    over = 1.06
    return [round(1 / (x * over), 2) for x in p]


def main() -> None:
    rng = random.Random(20260925)
    raw_dir = HERE / "data" / "raw" / "football_data"
    prov_dir = HERE / "data" / "provenance" / "football_data"
    raw_dir.mkdir(parents=True, exist_ok=True)
    prov_dir.mkdir(parents=True, exist_ok=True)
    expected = {}
    names = list(TEAMS)
    pairs = [(h, a) for h in names for a in names if h != a]
    for code, year in SEASONS.items():
        rng.shuffle(pairs)
        rows = []
        day = date(year, 8, 13)
        for i, (h, a) in enumerate(pairs):
            hg, ag = rng.choice([0, 1, 1, 2, 2, 3]), rng.choice([0, 0, 1, 1, 2])
            ftr = "H" if hg > ag else "A" if hg < ag else "D"
            time_ = "" if i % 5 == 4 else rng.choice(["15:00", "17:30", "20:00"])
            o, c = odds(rng), odds(rng)
            rows.append(
                [
                    "TST",
                    (day + timedelta(days=27 * i // 2 * 1)).strftime("%d/%m/%Y"),
                    time_,
                    RAW_ALIAS.get(h, h),
                    RAW_ALIAS.get(a, a),
                    hg,
                    ag,
                    ftr,
                    rng.randint(5, 20),
                    rng.randint(3, 15),
                    rng.randint(1, 8),
                    rng.randint(1, 6),
                    rng.randint(1, 9),
                    rng.randint(1, 8),
                    rng.randint(6, 16),
                    rng.randint(6, 16),
                    rng.randint(0, 4),
                    rng.randint(0, 4),
                    rng.randint(0, 1),
                    rng.randint(0, 1),
                    *o,
                    *c,
                    *o,
                    *c,
                ]
            )
        # deterministic chronological order; two matches per date so all four teams play weekly
        rows.sort(key=lambda r: (r[1][6:] + r[1][3:5] + r[1][:2], r[3]))
        path = raw_dir / f"TST_{code}.csv"
        with path.open("w", newline="", encoding="utf-8") as fh:
            w = csv.writer(fh, lineterminator="\n")
            w.writerow(HEADER)
            w.writerows(rows)
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        expected[path.name] = {
            "sha256": digest,
            "status": "pinned_observed",
            "basis": "synthetic fixture generated by generate_raw.py",
        }
        (prov_dir / f"{path.name}.json").write_text(
            json.dumps(
                {
                    "filename": path.name,
                    "source_id": "manual",
                    "source_url": "file://generate_raw.py",
                    "origin": "manual",
                    "retrieved_at_utc": "2026-09-25T00:00:00+00:00",
                    "sha256": digest,
                    "note": "synthetic test fixture",
                },
                indent=2,
                sort_keys=True,
            )
        )
    (HERE / "data" / "expected_checksums.json").write_text(
        json.dumps({"schema": 1, "files": expected}, indent=2, sort_keys=True)
    )
    import yaml

    teams = [{"team_id": f"TST_{s}", "canonical_name": n, "country": "TST"} for n, s in TEAMS.items()]
    aliases = [
        {
            "source": "football-data",
            "raw_name": RAW_ALIAS.get(n, n),
            "team_id": f"TST_{s}",
            "valid_from": None,
            "valid_to": None,
            "provenance": "manual",
            "approved_by": "fixture-generator",
            "confidence": 1.0,
        }
        for n, s in TEAMS.items()
    ]
    (HERE / "configs" / "team_aliases.yaml").write_text(
        yaml.safe_dump({"teams": teams, "aliases": aliases}, sort_keys=False)
    )

    for f in HERE.rglob("*"):  # committed golden files must be LF-only on every OS (checksums!)
        if f.is_file():
            f.write_bytes(f.read_bytes().replace(b"\r\n", b"\n"))


if __name__ == "__main__":
    main()
